GestionReparacion.CapaPresentacion/Controllers/PedidoComponenteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestionReparacion.CapaDominio.Entidades;
using GestionReparacion.CapaAplicacion.Servicios;

namespace GestionReparacion.CapaPresentacion.Controllers
{
    public class PedidoComponenteController : Controller
    {
        List<Componente> componentes = new List<Componente>();
        List<PedidoComponente> pedidoComponentes = new List<PedidoComponente>();
        Cliente cliente = new Cliente();
        Venta venta = new Venta();

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string dni)
        {
            var gestionarReparacionDispositivoServicio = new GestionarReparacionDispositivoService();
            cliente = gestionarReparacionDispositivoServicio.obtenerCliente(dni);

            if (cliente != null)
            {
                Session["Cliente"] = cliente;
                return RedirectToAction("BuscarComponentes");
            }
            else
            {
                return View();
            }

        }

        [HttpGet]
        public ActionResult BuscarComponentes()
        {
            if (Session["Cliente"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                Session["pedidoComponentes"] = pedidoComponentes;
                return View((List<Componente>)Session["ListaComponentes"]);
            }
        }

        [HttpPost]
        public ActionResult BuscarComponentes(string categoria)
        {
            var gestionarReparacionDispositivos = new GestionarReparacionDispositivoService();

            componentes = gestionarReparacionDispositivos.buscarComponentes(categoria);

            Session["ListaComponentes"] = componentes;

            return View(componentes);
        }

        [HttpGet]
        public ActionResult AgregarComponentes(int cantidad, int componenteId)
        {
            PedidoComponente pedido = new PedidoComponente();
            componentes = (List<Componente>)Session["ListaComponentes"];
            pedidoComponentes = (List<PedidoComponente>)Session["pedidoComponentes"];

            Session["Venta"] = venta;

            try
            {

                foreach (var item in componentes)
                {
                    if (item.IdComponente == componenteId) pedido.Componente = item;
                }

                pedido.CantidadComponentes = cantidad;

                var gestionarReparacionDispositivos = new GestionarReparacionDispositivoService();

                gestionarReparacionDispositivos.añadirPedido(pedido, ref pedidoComponentes);

            }
            catch (Exception e)
            {
                ((Venta)Session["Venta"]).ListaPedidoComponentes = pedidoComponentes;

                return Json(new { respuesta = false, mensaje = e.Message }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { respuesta = true}, JsonRequestBehavior.AllowGet );
        }

        [HttpGet]
        public ActionResult ListarPedido()
        {
            var gestionarReparacionDispositivos = new GestionarReparacionDispositivoService();

            venta = (Venta)Session["Venta"];
            venta.ListaPedidoComponentes = ((List<PedidoComponente>)Session["pedidoComponentes"]);

            ViewBag.CostoComponentes = gestionarReparacionDispositivos.
                obtenerCostoPedido(venta);

            return View(venta.ListaPedidoComponentes);
        }

        [HttpGet]
        public ActionResult AgregarEnsamblado(Boolean ensamblado)
        {
            var gestionarReparacionDispositivos = new GestionarReparacionDispositivoService();
            string mensaje = "";

            venta.ListaPedidoComponentes = ((List<PedidoComponente>)Session["pedidoComponentes"]);
            venta.EsServicioDeEnsamblajeAceptado = ensamblado;

            try
            {
                if (ensamblado)
                {
                    ViewBag.CostoComponentes = gestionarReparacionDispositivos.
                        agregarServicioEnsamblado(venta);

                    mensaje = "Se agrego el servicio de ensamblado";
                }

                else
                {
                    ViewBag.CostoComponentes = gestionarReparacionDispositivos.
                        obtenerCostoPedido(venta);

                    mensaje = "Se quito el servicio de ensamblado";
                }
            }
            catch (Exception e)
            {
                return Json(new { respuesta = false, e.Message }, JsonRequestBehavior.AllowGet);
            }

            Session["Venta"] = venta;

            return Json(new { respuesta = true, mensaje, costo = ViewBag.CostoComponentes }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult PagarComponente()
        {
            venta = (Venta)Session["Venta"];

            var gestionarReparacionDispositivos = new GestionarReparacionDispositivoService();

            ViewBag.CostoComponentes = gestionarReparacionDispositivos.
                obtenerCostoPedido(venta);

            ViewBag.CostoEnsamblaje = gestionarReparacionDispositivos.
                obtenerCostoEnsamblado(venta);

            ViewBag.CostoTotal = gestionarReparacionDispositivos.
                obtenerCostoTotal(venta);

            return View();
        }

        [HttpPost]
        public ActionResult GuardarPedido(string numTarjeta, string numCsc)
        {
            venta = (Venta)Session["Venta"];
            
            var gestionarReparacionDispositivos = new GestionarReparacionDispositivoService();

            TarjetaDePago tarjetaDePago = new TarjetaDePago();

            tarjetaDePago.CodigoCSC = numCsc;
            tarjetaDePago.NumeroDeTarjeta = numTarjeta;

            gestionarReparacionDispositivos.guardarPedido(tarjetaDePago, venta, (Cliente)Session["Cliente"]);

            return RedirectToAction("MostrarInformeDetallado");
        }

        [HttpGet]
        public ActionResult MostrarInformeDetallado()
        {
            venta = (Venta)Session["Venta"];

            var gestionarReparacionDispositivos = new GestionarReparacionDispositivoService();

            ViewBag.CostoComponentes = gestionarReparacionDispositivos.
                obtenerCostoPedido(venta);

            ViewBag.CostoEnsamblaje = gestionarReparacionDispositivos.
                obtenerCostoEnsamblado(venta);

            ViewBag.CostoTotal = gestionarReparacionDispositivos.
                obtenerCostoTotal(venta);

            return View(venta);
        }
    }
}

GestionReparacion.CapaPresentacion/Views/PedidoComponente/BuscarComponentes.cshtml
@model List<GestionReparacion.CapaDominio.Entidades.Componente>

@{
    ViewBag.Title = "BuscarComponentes";
}

<div class="container margin-nav">
    <div class="text-center">
        <h2 class="section-heading text-uppercase"> Buscar Componentes </h2>
        <h4 class="section-subheading text-muted contain-text py-3">
            <i>
                Acá puedes escoger entre una gran variedad de componentes para tu equipo,
                los que selecciones se añadirán a tu pedido. &nbsp;
            </i> 😉
        </h4>
    </div>

    <form action="/PedidoComponente/BuscarComponentes" method="post">
        <div class="py-xl-5 row">
            <div class="btn-group btn-group-toggle col-sm-6" data-toggle="buttons">
                <label class="btn btn-lg btn-success active">
                    <input type="radio" name="categoria" value="Escritorio"
                           autocomplete="off"> Escritorio &nbsp; 🖥
                </label>
                <label class="btn btn-lg btn-success">
                    <input type="radio" name="categoria" value="Laptop"
                           autocomplete="off"> Laptop &nbsp; 💻
                </label>
                <label class="btn btn-lg btn-success">
                    <input type="radio" name="categoria" value="Movil"
                           autocomplete="off"> Movil &nbsp; 📱
                </label>
            </div>

            <button type="submit" class="btn btn-lg btn-info col-sm-4 ml-auto">
                Buscar Componente &nbsp; 🔎
            </button>
        </div>
    </form>

    <div class="table-responsive">
        <span class="counter pull-right"></span>

        @{ if (Model != null && Model.Count != 0)
            {
                <div id="tabla" class="my-xl-5">
                    <table id="info" style="margin:auto" width="100%" cellspacing="0" class="table table-bordered table-dark" lang="es">
                        <thead>
                            <tr align="center">
                                <th> Nombre </th>
                                <th> Precio </th>
                                <th> Tipo </th>
                                <th> Stock </th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td> @item.NombreComponente</td>
                                        <td align="center"> @item.Precio </td>
                                        <td align="center"> @item.Tipo </td>
                                        <td align="center"> @item.Stock </td>

                                        <td align="center" class="">
                                            <button class="btn btn-outline-success" value="create"
                                                    onclick="agregarCantidad(@item.IdComponente)">
                                                Agregar &nbsp; ➕
                                            </button>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>

                <div class="centrar" align="center">
                    <button class="btn btn-warning my-4 btn-lg" type="submit"
                        onclick="location.href='@Url.Action("ListarPedido", "PedidoComponente")'">
                        Ver Pedido &nbsp; 🛒
                    </button>
                </div>
            }
        }

    </div>

</div>



@section scripts
    {

    <script>

        function agregarCantidad(componete)
        {
            var cantidad_ = parseInt(prompt("Ingrese La Cantidad : "));            

            var error = "¡UPS!, La cantidad ingresada no es válida. ";

            if (cantidad_ == undefined || isNaN(cantidad_)) alert(error);

            if (cantidad_ == null || cantidad_ == "" ) alert(error);

            if (cantidad_ < 0) alert(error);

            $.ajax({
                type: "Get",
                url: "/PedidoComponente/AgregarComponentes",
                data: { cantidad: cantidad_, componenteId: componete},
                contentType: "application/json; charset=utf8",
                dataType: "json",
                success: function (respuesta, mensaje) {
                    alert(respuesta.mensaje);
                    },
                    error: function(xhr, ajaxOptions, thrownError) {

                    }
            })
        }

    </script>

}

GestionReparacion.CapaPresentacion/Views/PedidoComponente/ListarPedido.cshtml
@model List<GestionReparacion.CapaDominio.Entidades.PedidoComponente>

@{
    ViewBag.Title = "ListarPedido";
}

<div class="container margin-nav">
    <div class="text-center">
        <h2 class="section-heading text-uppercase"> Lista de Pedidos </h2>
        <h4 class="section-subheading text-muted contain-text py-3">
            <i>
                Acá se encuentran todos los componentes que acabas de agregar a tu lista &nbsp;
            </i> 😬
        </h4>
    </div>

    <div class="table-responsive">
        <span class="counter pull-right"></span>

        @{ if (Model != null && Model.Count != 0)
            {
                <div id="tabla" class="my-xl-5">
                    <table id="info" style="margin:auto" width="100%" cellspacing="0" class="table table-bordered table-dark" lang="es">
                        <thead>
                            <tr align="center">
                                <th> Nombre </th>
                                <th> Precio </th>
                                <th> Cantidad Adquirida </th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td> @item.Componente.NombreComponente</td>
                                        <td align="center"> @item.Componente.Precio </td>
                                        <td align="center"> @item.CantidadComponentes </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>

                <div class="centrar row " align="center">

                    <div class="alert alert-warning" role="alert">
                        El costo total es de : <label id="costoTotal" class="alert-link">
                            @ViewBag.CostoComponentes</label> &nbsp; 💰
                    </div>

                    <div class="custom-control custom-checkbox ml-auto my-2">
                        <input type="checkbox" class="custom-control-input" id="ensamblar">
                        <label class="custom-control-label" for="ensamblar">  &nbsp; Agregar servicio de ensamblado </label>
                    </div>

                </div>

                <div class="centrar my-xl-5">
                    <button class="btn btn-warning my-4 btn-lg" type="submit"
                            onclick="location.href='@Url.Action("PagarComponente", "PedidoComponente")'">
                        Pagar &nbsp; 💲
                    </button>
                </div>
            }
        }

    </div>

</div>



@section scripts
    {

    <script>

        $(document).on('change', '#ensamblar', function (e) {

            var ensamblar;

            if (this.checked) ensamblar = true;
            else ensamblar = false;

            $.ajax({
                type: "Get",
                url: "/PedidoComponente/AgregarEnsamblado",
                data: { ensamblado: ensamblar },
                contentType: "application/json; charset=utf8",
                dataType: "json",
                success: function (respuesta, mensaje, costo) {

                    //alert(respuesta.mensaje);
                    document.getElementById('costoTotal').innerHTML = respuesta.costo;

                }
            })
        });


    </script>

}

GestionReparacion.CapaPresentacion/Views/PedidoComponente/Login.cshtml
@model string

<title>Login Page</title>

<header class="masthead login-head">
    <div class="container h-100" style="margin-top:210px; margin-bottom:300px; transform:scale(1.2)">
        <div class="d-flex justify-content-center h-500">
            <div class="card card-login">
                <div class="card-header text-center">
                    <h3>Cliente 🧑🏻 </h3>
                </div>
                <hr style="background-color:darkgrey">
                <div class="card-body">
                    <form action="/PedidoComponente/Login" method="post">
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="dni" class="form-control" placeholder="DNI" minlength="8" maxlength="8" onkeypress="return soloNumeros(event)" required>
                        </div>
                        <div class="form-group centrar" style="margin-top:40px">
                            <input type="submit" value="Login" class="btn btn-outline-light">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</header>

@section scripts
    {

    <script>
        function soloNumeros(e) {
            var key = window.Event ? e.which : e.keyCode;
            if (key >= 48 && key <= 57 || key == 8 || key == 0) {
                return true;
            } else {
                return false;
            }
        }

    </script>
}

GestionReparacion.CapaPresentacion/Views/PedidoComponente/MostrarInformeDetallado.cshtml
@model GestionReparacion.CapaDominio.Entidades.Venta

@{
    ViewBag.Title = "ListarPedido";
}

    <div class="container margin-nav">
        <div class="text-center">
            <h2 class="section-heading text-uppercase"> Se hizo el pago correctamente ✔  </h2>
            <h4 class="section-subheading text-muted contain-text py-3">
                <i>
                    Acá tienes un informe detallado de lo que adquiriste &nbsp;
                </i> 📃
            </h4>
        </div>

        <div class="card text-white bg-warning col-sm-12 my-lg-5">
            <div class="card-header" align="center"> <h4> <strong> Total a Pagar </strong> </h4>  </div>
            <div class="card-body">

                @{
                    foreach (var item in Model.ListaPedidoComponentes)
                    {
                        <div class="row">
                            <h5 class="col-sm-9 my-2">
                                🔘
                                &nbsp;&nbsp; @item.Componente.NombreComponente
                            </h5>
                            <h5 class="ml-auto"> @item.calcularCostoTotal() S/ </h5>
                        </div>

                    }
                }

                <hr>

                <div class="row">
                    <h4 class="col-sm-9">
                        🔴
                        &nbsp;&nbsp;Costo de Ensamblaje

                    </h4>
                    <h4 class="ml-auto"> @ViewBag.CostoEnsamblaje S/</h4>
                </div>
                <hr>
                <div class="row py-3">
                    <h3 class="col-sm-9">
                        🔵
                        <strong>
                            &nbsp;&nbsp; Costo Total
                        </strong>
                    </h3>
                    <h3> @ViewBag.CostoTotal &nbsp; S/</h3>
                </div>

            </div>
        </div>




        <!--div class="alert alert-warning py-xl-5" role="alert">
    El costo total a pagar es de : <label id="costoTotal" class="alert-link">
    @ViewBag.CostoTotal
        </label> &nbsp; 💰
            </div-->
        <!--div class="custom-control custom-checkbox my-5 centrar">
        <input type="checkbox" class="custom-control-input" id="ensamblar">
        <label class="custom-control-label" for="ensamblar">  &nbsp; Agregar servicio de ensamblado </label>
    </!--div-->

        <div class="centrar my-xl-5">
            <button class="btn btn-info my-4 btn-lg" type="submit"
                    onclick="location.href='@Url.Action( "BuscarComponentes", "PedidoComponente")'">
                
                Ir a Inicio &nbsp; ➡
            </button>
        </div>
    </div>





@section scripts
    {

    <script>

        $(document).on('change', '#ensamblar', function (e) {

            var ensamblar;

            if (this.checked) ensamblar = true;
            else ensamblar = false;

            $.ajax({
                type: "Get",
                url: "/PedidoComponente/AgregarEnsamblado",
                data: { ensamblado: ensamblar },
                contentType: "application/json; charset=utf8",
                dataType: "json",
                success: function (respuesta, mensaje, costo) {

                    //alert(respuesta.mensaje);
                    document.getElementById('costoTotal').innerHTML = respuesta.costo;

                }
            })
        });


    </script>

}

GestionReparacion.CapaPresentacion/Views/PedidoComponente/PagarComponente.cshtml
@model List<GestionReparacion.CapaDominio.Entidades.PedidoComponente>

@{
    ViewBag.Title = "ListarPedido";
}

<div class="container margin-nav">
    <div class="text-center">
        <h2 class="section-heading text-uppercase"> Pagar Componentes </h2>
        <h4 class="section-subheading text-muted contain-text py-3">
            <i>
                Puede realizar el pago con su tarjeta de crédito, ni bien realice
                el pago nosotros efectuaremos el envío inmediatamente &nbsp;
            </i> 💳
        </h4>
    </div>

    <form action="/PedidoComponente/GuardarPedido" method="post">
        <div class="row py-xl-5">
            <div class="card text-white bg-success mb-3 col-sm-5 ml-xl-5">
                <div class="card-header" align="center"> <h4> <strong> Total a Pagar </strong> </h4>  </div>
                <div class="card-body">
                    <div class="row">
                        <h5 class="col-sm-9">
                            Costo de Componentes &nbsp;&nbsp;
                            <i class="fas fa-caret-square-right"></i>
                        </h5>
                        <h5 class="ml-auto"> @ViewBag.CostoComponentes /S </h5>
                    </div>
                    <div class="row">
                        <h5 class="col-sm-9">
                            Costo de Ensamblaje &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <i class="fas fa-caret-square-right"></i>
                        </h5>
                        <h5 class="ml-auto"> @ViewBag.CostoEnsamblaje /S </h5>
                    </div>
                    <hr>
                    <div class="row py-3">
                        <h4 class="col-sm-8">
                            <strong>
                                Costo Total &nbsp;&nbsp;&nbsp;
                            </strong><i class="fas fa-caret-square-right"></i>
                        </h4>
                        <h4> @ViewBag.CostoTotal &nbsp; /S </h4>
                    </div>
                </div>
            </div>

            <div class="card text-white bg-danger mb-3 col-sm-5 ml-xl-5" align="center">
                <div class="card-header"> <h4> <strong> Datos de su Tarjeta </strong> </h4>  </div>
                <div class="card-body">
                    <div class="input-group col-sm-11 py-3" style="transform:scale(1.2)">
                        <div class="input-group-prepend">
                            <span class="input-group-text"> <i class="fab fa-cc-visa"></i> </span>
                        </div>
                        <input type="text" class="form-control" placeholder="Numero de Tarjeta" 
                                onkeypress="if (event.keyCode < 48 || event.keyCode > 57) event.returnValue = false;"
                                maxlength="16" required="" pattern=".{16,16}" name="numTarjeta">
                    </div>
                    <div class="input-group col-sm-11 py-3" style="transform:scale(1.2)">
                        <div class="input-group-prepend">
                            <span class="input-group-text"> <i class="fas fa-credit-card"></i> </span>
                        </div>
                        <input type="text" class="form-control" placeholder="Codigo Secreto de Tarjeta de Credito" 
                                onkeypress="if (event.keyCode < 48 || event.keyCode > 57) event.returnValue = false;"
                                maxlength="3" required="" pattern=".{3,3}" name="numCsc">
                    </div>
                </div>
            </div>


            <!--div class="alert alert-warning py-xl-5" role="alert">
        El costo total a pagar es de : <label id="costoTotal" class="alert-link">
        @ViewBag.CostoTotal
            </label> &nbsp; 💰
                </div-->

            <!--div class="custom-control custom-checkbox my-5 centrar">
                <input type="checkbox" class="custom-control-input" id="ensamblar">
                <label class="custom-control-label" for="ensamblar">  &nbsp; Agregar servicio de ensamblado </label>
            </!--div-->

            <div class="centrar my-xl-5">
                <button class="btn btn-warning my-4 btn-lg" type="submit">
                    Pagar &nbsp; 💲
                </button>
            </div>
        </div>
    </form>
</div>



@section scripts
    {

    <script>

        $(document).on('change', '#ensamblar', function (e) {

            var ensamblar;

            if (this.checked) ensamblar = true;
            else ensamblar = false;

            $.ajax({
                type: "Get",
                url: "/PedidoComponente/AgregarEnsamblado",
                data: { ensamblado: ensamblar },
                contentType: "application/json; charset=utf8",
                dataType: "json",
                success: function (respuesta, mensaje, costo) {

                    //alert(respuesta.mensaje);
                    document.getElementById('costoTotal').innerHTML = respuesta.costo;

                }
            })
        });


    </script>

}